// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.systems.dhruva.modal;

import com.systems.dhruva.modal.ActionCase;
import com.systems.dhruva.modal.ActionCaseDataOnDemand;
import com.systems.dhruva.modal.ActionCaseIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ActionCaseIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ActionCaseIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ActionCaseIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ActionCaseIntegrationTest: @Transactional;
    
    @Autowired
    ActionCaseDataOnDemand ActionCaseIntegrationTest.dod;
    
    @Test
    public void ActionCaseIntegrationTest.testCountActionCases() {
        Assert.assertNotNull("Data on demand for 'ActionCase' failed to initialize correctly", dod.getRandomActionCase());
        long count = ActionCase.countActionCases();
        Assert.assertTrue("Counter for 'ActionCase' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ActionCaseIntegrationTest.testFindActionCase() {
        ActionCase obj = dod.getRandomActionCase();
        Assert.assertNotNull("Data on demand for 'ActionCase' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ActionCase' failed to provide an identifier", id);
        obj = ActionCase.findActionCase(id);
        Assert.assertNotNull("Find method for 'ActionCase' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ActionCase' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ActionCaseIntegrationTest.testFindAllActionCases() {
        Assert.assertNotNull("Data on demand for 'ActionCase' failed to initialize correctly", dod.getRandomActionCase());
        long count = ActionCase.countActionCases();
        Assert.assertTrue("Too expensive to perform a find all test for 'ActionCase', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ActionCase> result = ActionCase.findAllActionCases();
        Assert.assertNotNull("Find all method for 'ActionCase' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ActionCase' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ActionCaseIntegrationTest.testFindActionCaseEntries() {
        Assert.assertNotNull("Data on demand for 'ActionCase' failed to initialize correctly", dod.getRandomActionCase());
        long count = ActionCase.countActionCases();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ActionCase> result = ActionCase.findActionCaseEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ActionCase' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ActionCase' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ActionCaseIntegrationTest.testFlush() {
        ActionCase obj = dod.getRandomActionCase();
        Assert.assertNotNull("Data on demand for 'ActionCase' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ActionCase' failed to provide an identifier", id);
        obj = ActionCase.findActionCase(id);
        Assert.assertNotNull("Find method for 'ActionCase' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyActionCase(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ActionCase' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ActionCaseIntegrationTest.testMergeUpdate() {
        ActionCase obj = dod.getRandomActionCase();
        Assert.assertNotNull("Data on demand for 'ActionCase' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ActionCase' failed to provide an identifier", id);
        obj = ActionCase.findActionCase(id);
        boolean modified =  dod.modifyActionCase(obj);
        Integer currentVersion = obj.getVersion();
        ActionCase merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ActionCase' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ActionCaseIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ActionCase' failed to initialize correctly", dod.getRandomActionCase());
        ActionCase obj = dod.getNewTransientActionCase(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ActionCase' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ActionCase' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ActionCase' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ActionCaseIntegrationTest.testRemove() {
        ActionCase obj = dod.getRandomActionCase();
        Assert.assertNotNull("Data on demand for 'ActionCase' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ActionCase' failed to provide an identifier", id);
        obj = ActionCase.findActionCase(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ActionCase' with identifier '" + id + "'", ActionCase.findActionCase(id));
    }
    
}
