// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.systems.dhruva.modal;

import com.systems.dhruva.modal.ActionStep;
import com.systems.dhruva.modal.ActionStepDataOnDemand;
import com.systems.dhruva.modal.ActionStepIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ActionStepIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ActionStepIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ActionStepIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ActionStepIntegrationTest: @Transactional;
    
    @Autowired
    ActionStepDataOnDemand ActionStepIntegrationTest.dod;
    
    @Test
    public void ActionStepIntegrationTest.testCountActionSteps() {
        Assert.assertNotNull("Data on demand for 'ActionStep' failed to initialize correctly", dod.getRandomActionStep());
        long count = ActionStep.countActionSteps();
        Assert.assertTrue("Counter for 'ActionStep' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ActionStepIntegrationTest.testFindActionStep() {
        ActionStep obj = dod.getRandomActionStep();
        Assert.assertNotNull("Data on demand for 'ActionStep' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ActionStep' failed to provide an identifier", id);
        obj = ActionStep.findActionStep(id);
        Assert.assertNotNull("Find method for 'ActionStep' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ActionStep' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ActionStepIntegrationTest.testFindAllActionSteps() {
        Assert.assertNotNull("Data on demand for 'ActionStep' failed to initialize correctly", dod.getRandomActionStep());
        long count = ActionStep.countActionSteps();
        Assert.assertTrue("Too expensive to perform a find all test for 'ActionStep', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ActionStep> result = ActionStep.findAllActionSteps();
        Assert.assertNotNull("Find all method for 'ActionStep' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ActionStep' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ActionStepIntegrationTest.testFindActionStepEntries() {
        Assert.assertNotNull("Data on demand for 'ActionStep' failed to initialize correctly", dod.getRandomActionStep());
        long count = ActionStep.countActionSteps();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ActionStep> result = ActionStep.findActionStepEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ActionStep' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ActionStep' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ActionStepIntegrationTest.testFlush() {
        ActionStep obj = dod.getRandomActionStep();
        Assert.assertNotNull("Data on demand for 'ActionStep' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ActionStep' failed to provide an identifier", id);
        obj = ActionStep.findActionStep(id);
        Assert.assertNotNull("Find method for 'ActionStep' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyActionStep(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ActionStep' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ActionStepIntegrationTest.testMergeUpdate() {
        ActionStep obj = dod.getRandomActionStep();
        Assert.assertNotNull("Data on demand for 'ActionStep' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ActionStep' failed to provide an identifier", id);
        obj = ActionStep.findActionStep(id);
        boolean modified =  dod.modifyActionStep(obj);
        Integer currentVersion = obj.getVersion();
        ActionStep merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ActionStep' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ActionStepIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ActionStep' failed to initialize correctly", dod.getRandomActionStep());
        ActionStep obj = dod.getNewTransientActionStep(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ActionStep' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ActionStep' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ActionStep' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ActionStepIntegrationTest.testRemove() {
        ActionStep obj = dod.getRandomActionStep();
        Assert.assertNotNull("Data on demand for 'ActionStep' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ActionStep' failed to provide an identifier", id);
        obj = ActionStep.findActionStep(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ActionStep' with identifier '" + id + "'", ActionStep.findActionStep(id));
    }
    
}
