// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.systems.dhruva.modal;

import com.systems.dhruva.modal.ActionCase;
import com.systems.dhruva.modal.ActionCaseDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ActionCaseDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ActionCaseDataOnDemand: @Component;
    
    private Random ActionCaseDataOnDemand.rnd = new SecureRandom();
    
    private List<ActionCase> ActionCaseDataOnDemand.data;
    
    public ActionCase ActionCaseDataOnDemand.getNewTransientActionCase(int index) {
        ActionCase obj = new ActionCase();
        setAssignedTo(obj, index);
        setBrowser(obj, index);
        setDefectTool(obj, index);
        setReportedBy(obj, index);
        return obj;
    }
    
    public void ActionCaseDataOnDemand.setAssignedTo(ActionCase obj, int index) {
        String assignedTo = "assignedTo_" + index;
        obj.setAssignedTo(assignedTo);
    }
    
    public void ActionCaseDataOnDemand.setBrowser(ActionCase obj, int index) {
        String browser = "browser_" + index;
        obj.setBrowser(browser);
    }
    
    public void ActionCaseDataOnDemand.setDefectTool(ActionCase obj, int index) {
        String defectTool = "defectTool_" + index;
        obj.setDefectTool(defectTool);
    }
    
    public void ActionCaseDataOnDemand.setReportedBy(ActionCase obj, int index) {
        String reportedBy = "reportedBy_" + index;
        obj.setReportedBy(reportedBy);
    }
    
    public ActionCase ActionCaseDataOnDemand.getSpecificActionCase(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ActionCase obj = data.get(index);
        Long id = obj.getId();
        return ActionCase.findActionCase(id);
    }
    
    public ActionCase ActionCaseDataOnDemand.getRandomActionCase() {
        init();
        ActionCase obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ActionCase.findActionCase(id);
    }
    
    public boolean ActionCaseDataOnDemand.modifyActionCase(ActionCase obj) {
        return false;
    }
    
    public void ActionCaseDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ActionCase.findActionCaseEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ActionCase' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ActionCase>();
        for (int i = 0; i < 10; i++) {
            ActionCase obj = getNewTransientActionCase(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
