// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.systems.dhruva.modal;

import com.systems.dhruva.modal.ActionStep;
import com.systems.dhruva.modal.ActionStepDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ActionStepDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ActionStepDataOnDemand: @Component;
    
    private Random ActionStepDataOnDemand.rnd = new SecureRandom();
    
    private List<ActionStep> ActionStepDataOnDemand.data;
    
    public ActionStep ActionStepDataOnDemand.getNewTransientActionStep(int index) {
        ActionStep obj = new ActionStep();
        setCommand(obj, index);
        setErrorDetails(obj, index);
        setErrorMessage(obj, index);
        setExpectedResult(obj, index);
        setSelectorType(obj, index);
        setTargetLocator(obj, index);
        setTestResult(obj, index);
        return obj;
    }
    
    public void ActionStepDataOnDemand.setCommand(ActionStep obj, int index) {
        String command = "command_" + index;
        obj.setCommand(command);
    }
    
    public void ActionStepDataOnDemand.setErrorDetails(ActionStep obj, int index) {
        String errorDetails = "errorDetails_" + index;
        obj.setErrorDetails(errorDetails);
    }
    
    public void ActionStepDataOnDemand.setErrorMessage(ActionStep obj, int index) {
        String errorMessage = "errorMessage_" + index;
        obj.setErrorMessage(errorMessage);
    }
    
    public void ActionStepDataOnDemand.setExpectedResult(ActionStep obj, int index) {
        String expectedResult = "expectedResult_" + index;
        obj.setExpectedResult(expectedResult);
    }
    
    public void ActionStepDataOnDemand.setSelectorType(ActionStep obj, int index) {
        String selectorType = "selectorType_" + index;
        obj.setSelectorType(selectorType);
    }
    
    public void ActionStepDataOnDemand.setTargetLocator(ActionStep obj, int index) {
        String targetLocator = "targetLocator_" + index;
        obj.setTargetLocator(targetLocator);
    }
    
    public void ActionStepDataOnDemand.setTestResult(ActionStep obj, int index) {
        String testResult = "testResult_" + index;
        obj.setTestResult(testResult);
    }
    
    public ActionStep ActionStepDataOnDemand.getSpecificActionStep(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ActionStep obj = data.get(index);
        Long id = obj.getId();
        return ActionStep.findActionStep(id);
    }
    
    public ActionStep ActionStepDataOnDemand.getRandomActionStep() {
        init();
        ActionStep obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ActionStep.findActionStep(id);
    }
    
    public boolean ActionStepDataOnDemand.modifyActionStep(ActionStep obj) {
        return false;
    }
    
    public void ActionStepDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ActionStep.findActionStepEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ActionStep' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ActionStep>();
        for (int i = 0; i < 10; i++) {
            ActionStep obj = getNewTransientActionStep(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
