// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.systems.dhruva.modal;

import com.systems.dhruva.modal.ClientIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ClientIntegrationTest_Roo_Configurable {
    
    declare @type: ClientIntegrationTest: @Configurable;
    
}
