// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.systems.dhruva.modal;

import com.systems.dhruva.modal.FileUpload;
import com.systems.dhruva.modal.FileUploadDataOnDemand;
import com.systems.dhruva.modal.FileUploadIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FileUploadIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FileUploadIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FileUploadIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FileUploadIntegrationTest: @Transactional;
    
    @Autowired
    FileUploadDataOnDemand FileUploadIntegrationTest.dod;
    
    @Test
    public void FileUploadIntegrationTest.testCountFileUploads() {
        Assert.assertNotNull("Data on demand for 'FileUpload' failed to initialize correctly", dod.getRandomFileUpload());
        long count = FileUpload.countFileUploads();
        Assert.assertTrue("Counter for 'FileUpload' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FileUploadIntegrationTest.testFindFileUpload() {
        FileUpload obj = dod.getRandomFileUpload();
        Assert.assertNotNull("Data on demand for 'FileUpload' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FileUpload' failed to provide an identifier", id);
        obj = FileUpload.findFileUpload(id);
        Assert.assertNotNull("Find method for 'FileUpload' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'FileUpload' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FileUploadIntegrationTest.testFindAllFileUploads() {
        Assert.assertNotNull("Data on demand for 'FileUpload' failed to initialize correctly", dod.getRandomFileUpload());
        long count = FileUpload.countFileUploads();
        Assert.assertTrue("Too expensive to perform a find all test for 'FileUpload', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<FileUpload> result = FileUpload.findAllFileUploads();
        Assert.assertNotNull("Find all method for 'FileUpload' illegally returned null", result);
        Assert.assertTrue("Find all method for 'FileUpload' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FileUploadIntegrationTest.testFindFileUploadEntries() {
        Assert.assertNotNull("Data on demand for 'FileUpload' failed to initialize correctly", dod.getRandomFileUpload());
        long count = FileUpload.countFileUploads();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<FileUpload> result = FileUpload.findFileUploadEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'FileUpload' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'FileUpload' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FileUploadIntegrationTest.testFlush() {
        FileUpload obj = dod.getRandomFileUpload();
        Assert.assertNotNull("Data on demand for 'FileUpload' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FileUpload' failed to provide an identifier", id);
        obj = FileUpload.findFileUpload(id);
        Assert.assertNotNull("Find method for 'FileUpload' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFileUpload(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'FileUpload' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FileUploadIntegrationTest.testMergeUpdate() {
        FileUpload obj = dod.getRandomFileUpload();
        Assert.assertNotNull("Data on demand for 'FileUpload' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FileUpload' failed to provide an identifier", id);
        obj = FileUpload.findFileUpload(id);
        boolean modified =  dod.modifyFileUpload(obj);
        Integer currentVersion = obj.getVersion();
        FileUpload merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'FileUpload' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FileUploadIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'FileUpload' failed to initialize correctly", dod.getRandomFileUpload());
        FileUpload obj = dod.getNewTransientFileUpload(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'FileUpload' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'FileUpload' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'FileUpload' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FileUploadIntegrationTest.testRemove() {
        FileUpload obj = dod.getRandomFileUpload();
        Assert.assertNotNull("Data on demand for 'FileUpload' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FileUpload' failed to provide an identifier", id);
        obj = FileUpload.findFileUpload(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'FileUpload' with identifier '" + id + "'", FileUpload.findFileUpload(id));
    }
    
}
